### ISSUE TITLE
Fix README.MD instructions

### ISSUE THREAD

**Issue by bgpanw** [medoix/malicious-docker#1]
Hi,
When following your instructions they just need some updates to the code block there.
You've written "gitlab.com" instead of "github.com" and also the name of the repo needs to be "malicious-docker" and not "malicious-test-docker" 

so this properly clones this repo and executes CD as it is today:
` git clone https://github.com/medoix/malicious-docker.git && cd malicious-docker`

Next, when building the Docker image, there are some errors. I realize the proejct is already very old but I still wanted to share:
 => ERROR [3/4] RUN go get -u github.com/alphasoc/flightsim/...  

I haven't looked into that yet and anything further....

EDIT: fixed the go build...
1) ensure that the Go programming language is installed
2) current instruction from the "alphasoc/flightsim" repo is:
`go install github.com/alphasoc/flightsim@latest`
3) fix the RUN command in step 3 with the above

Now the Docker build completes :-)

**Comment by medoix** [comment]
Thanks for the feedback. I have corrected all of the above in https://github.com/medoix/malicious-docker/commit/872ca25b4bff6e8ed3e2683eb7dd20dc965d7bdc
